/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Core;
import model.Pobocka;
import model.componentes.KnihaTableModel;
import model.componentes.PobockaTableModel;
import model.componentes.MyTableModel;
import test.Test;

/**
 *
 * @author Jožko
 */
public class BaseForm extends javax.swing.JFrame {

    private test.Test test;
    private Core core;
    private MyTableModel modelPob;
    private MyTableModel modelKnihy;

    /**
     * Creates new form BaseForm
     */
    public BaseForm() {
        initComponents();
        core = new Core();

        modelPob = new PobockaTableModel(core.getPobocky().getTableRows());
        tabPobocky.setModel(modelPob);

        modelKnihy = new KnihaTableModel(new ArrayList<>());
        pobTabKnihy.setModel(modelKnihy);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testAreaVypis = new javax.swing.JTextArea();
        testTxtPocOper = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        testTxtPravVloz = new javax.swing.JTextField();
        testBtnStart = new javax.swing.JButton();
        testBtnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabPobocky = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pobTxtNazov = new javax.swing.JTextField();
        pobBtnAdd = new javax.swing.JButton();
        pobBtnDel = new javax.swing.JButton();
        pobBtnCount = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pobTabKnihy = new javax.swing.JTable();
        pobBtnDelKnih = new javax.swing.JButton();
        pobPridKnih = new javax.swing.JButton();
        pobBtnRefreshKnih = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fileBtnSave = new javax.swing.JMenuItem();
        fileBtnLoad = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testAreaVypis.setColumns(20);
        testAreaVypis.setRows(5);
        jScrollPane1.setViewportView(testAreaVypis);

        testTxtPocOper.setText("100000");

        jLabel1.setText("Počet operácií");

        jLabel2.setText("Pravdepodobnosť vloženia");

        testTxtPravVloz.setText("0.7");

        testBtnStart.setText("Štart");
        testBtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnStartActionPerformed(evt);
            }
        });

        testBtnDelete.setText("Vymaž");
        testBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testTxtPravVloz, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testTxtPocOper, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(testBtnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testBtnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testTxtPocOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testTxtPravVloz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(testBtnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(testBtnDelete)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Testovanie", jPanel1);

        tabPobocky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabPobocky.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tabPobocky);
        tabPobocky.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel3.setText("Názov pobočky");

        pobBtnAdd.setText("Pridaj");
        pobBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnAddActionPerformed(evt);
            }
        });

        pobBtnDel.setText("Vymaž");
        pobBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnDelActionPerformed(evt);
            }
        });

        pobBtnCount.setText("Počet");
        pobBtnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnCountActionPerformed(evt);
            }
        });

        pobTabKnihy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(pobTabKnihy);

        pobBtnDelKnih.setText("Vymaž");

        pobPridKnih.setText("Pridaj");
        pobPridKnih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobPridKnihActionPerformed(evt);
            }
        });

        pobBtnRefreshKnih.setText("Refresh");
        pobBtnRefreshKnih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnRefreshKnihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(pobPridKnih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pobBtnDelKnih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pobBtnRefreshKnih)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pobBtnDelKnih)
                    .addComponent(pobPridKnih)
                    .addComponent(pobBtnRefreshKnih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Knihy", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Požičané knihy", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pobTxtNazov, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pobBtnAdd))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pobBtnDel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pobBtnCount)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pobTxtNazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pobBtnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pobBtnDel)
                    .addComponent(pobBtnCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pobočky", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Knihy", jPanel3);

        jMenu1.setText("File");

        fileBtnSave.setText("Save");
        fileBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnSaveActionPerformed(evt);
            }
        });
        jMenu1.add(fileBtnSave);

        fileBtnLoad.setText("Load");
        fileBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnLoadActionPerformed(evt);
            }
        });
        jMenu1.add(fileBtnLoad);

        jMenuItem2.setText("Koniec");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pobBtnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnCountActionPerformed
        System.out.println("Počet pobočiek:" + core.getPobocky().getCount());
    }//GEN-LAST:event_pobBtnCountActionPerformed

    private void pobBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnDelActionPerformed
        int row = tabPobocky.getSelectedRow();

        if (row > -1) {

            String name = (String) modelPob.getValueAt(row, PobockaTableModel.name);
            if (core.delPobocku(name)) {
                showInf("Pobočka bola vymazaná");
                refreshTabPoboc();
            } else {
                showInf("Pobočku sa nepodarilo vymazať");

            }
        }
    }//GEN-LAST:event_pobBtnDelActionPerformed

    private void pobBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnAddActionPerformed

        String name = pobTxtNazov.getText();
        if (name.equals("")) {

            showErr("Nezadali ste názov pobočky");

        } else {

            core.addPobocku(name);
            refreshTabPoboc();
            pobTxtNazov.setText("");

        }

    }//GEN-LAST:event_pobBtnAddActionPerformed

    private void testBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnDeleteActionPerformed
        testAreaVypis.setText("");
    }//GEN-LAST:event_testBtnDeleteActionPerformed

    private void testBtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnStartActionPerformed
        // TODO add your handling code here:

        try {

            test = new Test();

            int pocOper = Integer.parseInt(testTxtPocOper.getText());
            double prav = Double.parseDouble(testTxtPravVloz.getText());

            testAreaVypis.setText("");
            test.setPocOperaci(pocOper);
            test.setParvInsert(1 - prav);
            testAreaVypis.setText(test.result());
            test.testuj();
            testAreaVypis.append("\n" + test.result());

        } catch (NumberFormatException e) {
            showErr("Zlý formát vstupov");
        } catch (Exception e) {
            showErr(e.getMessage());
        }
    }//GEN-LAST:event_testBtnStartActionPerformed

    private void pobPridKnihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobPridKnihActionPerformed

        Pobocka pob = getPobocku();

        if (pob != null) {

            dlgKniha dlg = new dlgKniha(this, pob, null);
            dlg.setVisible(true);

            if (dlg.result) {
                refreshTabKniha(pob);
            }
        }


    }//GEN-LAST:event_pobPridKnihActionPerformed

    private void pobBtnRefreshKnihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnRefreshKnihActionPerformed

        refreshTabKniha(getPobocku());
    }//GEN-LAST:event_pobBtnRefreshKnihActionPerformed

    private void fileBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnSaveActionPerformed
        // TODO add your handling code here:
        core.save();
    }//GEN-LAST:event_fileBtnSaveActionPerformed

    private void fileBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnLoadActionPerformed
     
        core.loadfromTxt();
        refreshTabPoboc();
        
    }//GEN-LAST:event_fileBtnLoadActionPerformed

    public Pobocka getPobocku() {

        int row = tabPobocky.getSelectedRow();

        if (row > -1) {

            String name = (String) modelPob.getValueAt(row, PobockaTableModel.name);
            Pobocka pob = core.findPobocku(name);
            return pob;
        } else {
            showErr("Nie je vybratá žiadna pobočka");
            return null;
        }

    }

    private void refreshTabPoboc() {
        tabPobocky.removeAll();
        modelPob.setRows(core.getPobocky().getTableRows());
        tabPobocky.setModel(modelPob);
        tabPobocky.repaint();
        tabPobocky.updateUI();

    }

    private void refreshTabKniha(Pobocka pob) {
        pobTabKnihy.removeAll();
        if (pob != null) {
            modelKnihy.setRows(pob.getKnihyStr().getTableRows());
            pobTabKnihy.setModel(modelKnihy);
        }
        pobTabKnihy.repaint();
        pobTabKnihy.updateUI();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fileBtnLoad;
    private javax.swing.JMenuItem fileBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton pobBtnAdd;
    private javax.swing.JButton pobBtnCount;
    private javax.swing.JButton pobBtnDel;
    private javax.swing.JButton pobBtnDelKnih;
    private javax.swing.JButton pobBtnRefreshKnih;
    private javax.swing.JButton pobPridKnih;
    private javax.swing.JTable pobTabKnihy;
    private javax.swing.JTextField pobTxtNazov;
    private javax.swing.JTable tabPobocky;
    private javax.swing.JTextArea testAreaVypis;
    private javax.swing.JButton testBtnDelete;
    private javax.swing.JButton testBtnStart;
    private javax.swing.JTextField testTxtPocOper;
    private javax.swing.JTextField testTxtPravVloz;
    // End of variables declaration//GEN-END:variables

    /**
     * Zobrazi error msg
     *
     * @param msg text spravy
     */
    public void showErr(String msg) {

        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);

    }

    public void showInf(String msg) {

        JOptionPane.showMessageDialog(this, msg, "Info", JOptionPane.INFORMATION_MESSAGE);

    }

}
