/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.ListSelectionModel;
import system.Core;
import model.componentes.CitatelTableModel;
import model.componentes.KnihaTableModel;
import model.componentes.PobockaTableModel;
import model.componentes.MyTableModel;
import model.componentes.PozKnihaTableModel;
import system.IMessage;
import system.Message;
import test.Test;

/**
 *
 * @author Jožko
 */
public class BaseForm extends javax.swing.JFrame implements IMessage {

    private test.Test test;
    private Core core;
    private MyTableModel modelPob, // tabulka pobociek
            modelKnihy, // tabulka knih
            modelAllKnihy, // tabulka vsetkych knih
            modelCitatel, // tabulka citatelov
            modelAktPoz, // aktulane pozicky ciatatela
            modelHistPoz, // historia u citatela
            modelPozKnihy, // pobocka aktualne pozicane knihy
            modelOmesPoz;   // tabulka omeckanych vrateni pri citatelovi

    /**
     * Creates new form BaseForm
     */
    public BaseForm() {
        initComponents();
        core = new Core();
        core.addMsgListener(this);
        iniTables();

    }

    /**
     * Inicializacia tabuliek
     */
    private void iniTables() {
        modelPob = new PobockaTableModel();
        tabPobocky.setModel(modelPob);
        tabPobocky.setRowSelectionAllowed(true);
        tabPobocky.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelKnihy = new KnihaTableModel();
        pobTabKnihy.setModel(modelKnihy);
        pobTabKnihy.setRowSelectionAllowed(true);
        pobTabKnihy.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelAllKnihy = new KnihaTableModel();
        knihTbAll.setModel(modelAllKnihy);
        knihTbAll.setRowSelectionAllowed(true);
        knihTbAll.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelCitatel = new CitatelTableModel();
        tableCita.setModel(modelCitatel);
        tableCita.setRowSelectionAllowed(true);
        tableCita.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelAktPoz = new KnihaTableModel();
        tableAktPozic.setModel(modelAktPoz);
        tableAktPozic.setRowSelectionAllowed(true);
        tableAktPozic.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelHistPoz = new PozKnihaTableModel();
        tableHistPozic.setModel(modelHistPoz);
        tableHistPozic.setRowSelectionAllowed(true);
        tableHistPozic.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelOmesPoz = new PozKnihaTableModel();
        tableOmesPoz.setModel(modelOmesPoz);
        tableOmesPoz.setRowSelectionAllowed(true);
        tableOmesPoz.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        modelPozKnihy = new KnihaTableModel();
        pobTablPozKnihy.setModel(modelPozKnihy);
        pobTablPozKnihy.setRowSelectionAllowed(true);
        pobTablPozKnihy.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testAreaVypis = new javax.swing.JTextArea();
        testTxtPocOper = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        testTxtPravVloz = new javax.swing.JTextField();
        testBtnStart = new javax.swing.JButton();
        testBtnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabPobocky = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pobTxtNazov = new javax.swing.JTextField();
        pobBtnAdd = new javax.swing.JButton();
        pobBtnDel = new javax.swing.JButton();
        pobBtnCount = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pobTabKnihy = new javax.swing.JTable();
        pobBtnDelKnih = new javax.swing.JButton();
        pobPridKnih = new javax.swing.JButton();
        pobBtnRefreshKnih = new javax.swing.JButton();
        pobBtnPozic = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        checkNazov = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        pobTablPozKnihy = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pobBtnHladajPob = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        knihTbAll = new javax.swing.JTable();
        knihBtnRefres = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        knTxtHladaj = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        citTabPanel = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableAktPozic = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableHistPozic = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableOmesPoz = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableCita = new javax.swing.JTable();
        citBtnPridaj = new javax.swing.JButton();
        citBtnDel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        citTxtMeno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        citTxtPriez = new javax.swing.JTextField();
        citBtnRefreshDown = new javax.swing.JButton();
        citTxtId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nasTxtPocPob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nasTxtPocKnih = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nasTxtPocCit = new javax.swing.JTextField();
        nastBtnReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nasTxtPocNasled = new javax.swing.JTextField();
        dateChooser = new datechooser.beans.DateChooserCombo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fileBtnGener = new javax.swing.JMenuItem();
        fileBtnSave = new javax.swing.JMenuItem();
        fileBtnLoad = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");
        jMenu3.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabStateChanged(evt);
            }
        });

        testAreaVypis.setColumns(20);
        testAreaVypis.setRows(5);
        jScrollPane1.setViewportView(testAreaVypis);

        testTxtPocOper.setText("100000");

        jLabel1.setText("Počet operácií");

        jLabel2.setText("Pravdepodobnosť vloženia");

        testTxtPravVloz.setText("0.7");

        testBtnStart.setText("Štart");
        testBtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnStartActionPerformed(evt);
            }
        });

        testBtnDelete.setText("Vymaž");
        testBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testTxtPravVloz, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testTxtPocOper, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(testBtnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testBtnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testTxtPocOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testTxtPravVloz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(testBtnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(testBtnDelete)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTab.addTab("Testovanie", jPanel1);

        tabPobocky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabPobocky.setColumnSelectionAllowed(true);
        tabPobocky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPobockyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabPobocky);
        tabPobocky.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel3.setText("Názov pobočky");

        pobBtnAdd.setText("Pridaj");
        pobBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnAddActionPerformed(evt);
            }
        });

        pobBtnDel.setText("Vymaž");
        pobBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnDelActionPerformed(evt);
            }
        });

        pobBtnCount.setText("Počet");
        pobBtnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnCountActionPerformed(evt);
            }
        });

        pobTabKnihy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(pobTabKnihy);

        pobBtnDelKnih.setText("Vymaž");

        pobPridKnih.setText("Pridaj");
        pobPridKnih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobPridKnihActionPerformed(evt);
            }
        });

        pobBtnRefreshKnih.setText("Refresh");
        pobBtnRefreshKnih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnRefreshKnihActionPerformed(evt);
            }
        });

        pobBtnPozic.setText("Požičaj");
        pobBtnPozic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnPozicActionPerformed(evt);
            }
        });

        jButton2.setText("Hladaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        checkNazov.setSelected(true);
        checkNazov.setText("order by Nazov");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(pobPridKnih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pobBtnDelKnih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pobBtnPozic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(checkNazov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pobBtnRefreshKnih)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pobBtnDelKnih)
                    .addComponent(pobPridKnih)
                    .addComponent(pobBtnRefreshKnih)
                    .addComponent(pobBtnPozic)
                    .addComponent(jButton2)
                    .addComponent(checkNazov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Knihy", jPanel4);

        pobTablPozKnihy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(pobTablPozKnihy);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Meškajúce");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Požičané knihy", jPanel5);

        pobBtnHladajPob.setText("Hladaj");
        pobBtnHladajPob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobBtnHladajPobActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pobTxtNazov, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pobBtnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pobBtnHladajPob)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pobBtnDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pobBtnCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pobTxtNazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pobBtnAdd)
                    .addComponent(pobBtnHladajPob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pobBtnDel)
                    .addComponent(pobBtnCount)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTab.addTab("Pobočky", jPanel2);

        knihTbAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(knihTbAll);

        knihBtnRefres.setText("Refresh");
        knihBtnRefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knihBtnRefresActionPerformed(evt);
            }
        });

        jButton7.setText("Vráť knihu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Hladaj");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Vymaz");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(knTxtHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(knihBtnRefres)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(knihBtnRefres)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(knTxtHladaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTab.addTab("Knihy", jPanel3);

        tableAktPozic.setBackground(new java.awt.Color(153, 153, 153));
        tableAktPozic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tableAktPozic);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        citTabPanel.addTab("Aktuálne pôžičky", jPanel7);

        tableHistPozic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tableHistPozic);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        citTabPanel.addTab("História", jPanel8);

        tableOmesPoz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(tableOmesPoz);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        citTabPanel.addTab("Omeškania", jPanel9);

        tableCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tableCita);

        citBtnPridaj.setText("Pridaj");
        citBtnPridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citBtnPridajActionPerformed(evt);
            }
        });

        citBtnDel.setText("Vymaz");
        citBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citBtnDelActionPerformed(evt);
            }
        });

        jLabel4.setText("Meno");

        jLabel5.setText("Prizvisko");

        citBtnRefreshDown.setText("Refresh");
        citBtnRefreshDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citBtnRefreshDownActionPerformed(evt);
            }
        });

        jButton4.setText("Hladaj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citTabPanel)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(citTxtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(citBtnDel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(citTxtPriez, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(citBtnPridaj)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(citTxtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(citBtnRefreshDown)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citBtnPridaj)
                    .addComponent(jLabel4)
                    .addComponent(citTxtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(citTxtPriez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(citTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(citBtnDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(citBtnRefreshDown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(citTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTab.addTab("Citatelia", jPanel6);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Počet pobočiek");

        nasTxtPocPob.setText("5");

        jLabel7.setText("Počet knih");

        nasTxtPocKnih.setText("10");

        jLabel8.setText("Počet čitateľov");

        nasTxtPocCit.setText("10");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(nasTxtPocCit, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nasTxtPocPob)
                            .addComponent(nasTxtPocKnih, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nasTxtPocPob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nasTxtPocKnih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nasTxtPocCit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        nastBtnReset.setText("Reset");
        nastBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastBtnResetActionPerformed(evt);
            }
        });

        jLabel9.setText("Počet nasledovnikov");

        nasTxtPocNasled.setText("5");
        nasTxtPocNasled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nasTxtPocNasledFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(nasTxtPocNasled))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(nastBtnReset)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nastBtnReset)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nasTxtPocNasled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(435, Short.MAX_VALUE))
        );

        jTab.addTab("Nastavenia", jPanel10);

        jMenu1.setText("File");

        fileBtnGener.setText("Generuj");
        fileBtnGener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnGenerActionPerformed(evt);
            }
        });
        jMenu1.add(fileBtnGener);

        fileBtnSave.setText("Save");
        fileBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnSaveActionPerformed(evt);
            }
        });
        jMenu1.add(fileBtnSave);

        fileBtnLoad.setText("Load");
        fileBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnLoadActionPerformed(evt);
            }
        });
        jMenu1.add(fileBtnLoad);

        jMenuItem2.setText("Koniec");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTab)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Zobrazi pocet pobociek
     *
     * @param evt
     */
    private void pobBtnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnCountActionPerformed
        System.out.println("Počet pobočiek:" + core.getPobocky().getCount());
    }//GEN-LAST:event_pobBtnCountActionPerformed

    /**
     * Vymazanie pobocky
     *
     * @param evt
     */
    private void pobBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnDelActionPerformed
        int row = tabPobocky.getSelectedRow();
        String str = showInput("Zadajte pobocku kam sa presunie agenda.");
        if (str != null) {
            if (row > -1) {
                String name = (String) modelPob.getValueAt(row, PobockaTableModel.name);
                if (!str.isEmpty()) {
                    core.removePobocka(name, str);
                    showInf("Pobočka bola vymazaná");
                    refreshTabPoboc();

                }
            }
        }
    }//GEN-LAST:event_pobBtnDelActionPerformed

    /**
     * Pridanie pobocky
     *
     * @param evt
     */
    private void pobBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnAddActionPerformed

        String name = pobTxtNazov.getText();
        if (core.addPobocku(name)) {
            refreshTabPoboc();
            pobTxtNazov.setText("");
        }


    }//GEN-LAST:event_pobBtnAddActionPerformed

    /**
     * Vymzanie konzoly na testovacom tabe
     *
     * @param evt
     */
    private void testBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnDeleteActionPerformed
        testAreaVypis.setText("");
    }//GEN-LAST:event_testBtnDeleteActionPerformed

    /**
     * Testovanie
     *
     * @param evt
     */
    private void testBtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnStartActionPerformed
        // TODO add your handling code here:

        try {

            test = new Test();

            int pocOper = Integer.parseInt(testTxtPocOper.getText());
            double prav = Double.parseDouble(testTxtPravVloz.getText());

            testAreaVypis.setText("");
            test.setPocOperaci(pocOper);
            test.setParvInsert(1 - prav);
            testAreaVypis.setText(test.result());
            test.testuj();
            testAreaVypis.append("\n" + test.result());
            String res = "Prvky sa ";
            res += test.compare() == true ? "zhoduju" : "nezhoduju";
            testAreaVypis.append("\n" + res);
        } catch (NumberFormatException e) {
            showErr("Zlý formát vstupov");
        } catch (Exception e) {
            showErr(e.getMessage());
        }
    }//GEN-LAST:event_testBtnStartActionPerformed

    /**
     * Pridanie knihy na pobocku
     *
     * @param evt
     */
    private void pobPridKnihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobPridKnihActionPerformed

        String pob = getPobocku();
        if (!pob.isEmpty()) {

            dlgKniha dlg = new dlgKniha(this, core, pob, null);
            dlg.setVisible(true);

            if (dlg.result) {

                refreshTabKniha();

            }
        }


    }//GEN-LAST:event_pobPridKnihActionPerformed

    /**
     * Refreshne tabulku knih podla pobocky
     *
     * @param evt
     */
    private void pobBtnRefreshKnihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnRefreshKnihActionPerformed

        refreshTabKniha();
    }//GEN-LAST:event_pobBtnRefreshKnihActionPerformed

    /**
     * Ulozenie do suboru
     *
     * @param evt
     */
    private void fileBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnSaveActionPerformed
        // TODO add your handling code here:
        core.save();
    }//GEN-LAST:event_fileBtnSaveActionPerformed

    /**
     * Citanie so suboru
     *
     * @param evt
     */
    private void fileBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnLoadActionPerformed

        core.loadfromTxt();
        refreshTabPoboc();

    }//GEN-LAST:event_fileBtnLoadActionPerformed

    /**
     * Prekliknutie medzi tabmi
     *
     * @param evt
     */
    private void jTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabStateChanged
        switch (jTab.getSelectedIndex()) {

            case 2:
                refreshTabAllKnih();
                break;

        }
    }//GEN-LAST:event_jTabStateChanged

    /**
     * Obnovenie tabulky so vsetkymi knihami
     *
     * @param evt
     */
    private void knihBtnRefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knihBtnRefresActionPerformed
        refreshTabAllKnih();
    }//GEN-LAST:event_knihBtnRefresActionPerformed

    /**
     * Generator poloziek
     *
     * @param evt
     */
    private void fileBtnGenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnGenerActionPerformed

        int pocPob = Integer.parseInt(nasTxtPocPob.getText());
        int pocKnih = Integer.parseInt(nasTxtPocKnih.getText());
        int pocCit = Integer.parseInt(nasTxtPocCit.getText());
        core.setPocGenPob(pocPob);
        core.setPocGenKnih(pocKnih);
        core.setPocGenCit(pocCit);

        Thread tr = new Thread() {
            public void run() {

                core.generujData();
                refreshTabPoboc();
                refreshTabCit();

            }

        };

        tr.start();


    }//GEN-LAST:event_fileBtnGenerActionPerformed

    /**
     * Testovanie posunu v brw
     *
     * @param evt
     */
    private void pobBtnHladajPobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnHladajPobActionPerformed
        String str = pobTxtNazov.getText();
        refreshTabPoboc(core.findPobockuArray(str));

    }//GEN-LAST:event_pobBtnHladajPobActionPerformed

    /**
     * Kliknutie na brw
     *
     * @param evt
     */
    private void tabPobockyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPobockyMouseClicked
        if (evt.getClickCount() > 1) {

            showInf(String.valueOf(tabPobocky.getSelectedRow()));

        }
    }//GEN-LAST:event_tabPobockyMouseClicked

    /**
     * Pridanie citatela
     *
     * @param evt
     */
    private void citBtnPridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citBtnPridajActionPerformed

        String name = citTxtMeno.getText();
        String przv = citTxtPriez.getText();
        if (core.addCitatela(name, przv)) {
            refreshTabCit();
            citTxtMeno.setText("");
            citTxtPriez.setText("");
        } else {
            showErr("Nezadali ste meno alebo priezvisko");

        }


    }//GEN-LAST:event_citBtnPridajActionPerformed

    private void pobBtnPozicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobBtnPozicActionPerformed

        String str = JOptionPane.showInputDialog(this, "Zadajte čitatela");
        System.out.println(str);
        if (str != null) {
            if (str.isEmpty()) {
                showErr("Nevyplnili ste číslo čitateľa!");
            } else {
                int citatel = Integer.parseInt(str);

                core.urobPozicku(getPobocku(), getIdKnihy(), citatel, dateChooser.getCurrent());

                refreshTabPobPoz();
            }
        }

        //core.urobPozicku(null, null, WIDTH);
    }//GEN-LAST:event_pobBtnPozicActionPerformed

    private void citBtnRefreshDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citBtnRefreshDownActionPerformed

        switch (citTabPanel.getSelectedIndex()) {

            case 0:
                refreshTabCitPoz();
                break;
            case 1:
                refreshTabCitHistory();
                break;
            case 2:
                refreshTabCitOmeskan();
                break;

        }
    }//GEN-LAST:event_citBtnRefreshDownActionPerformed

    /**
     * Btn refresh pobocky
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refreshTabPoboc();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Hladaj knihu
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String result = "";
        ArrayList list = null;
        if (checkNazov.isSelected()) {
            result = showInput("Zadajte názov knihy");
            if (result != null) {
                list = core.findKnihuOfPobocka(getPobocku(), result);
            }
        } else {

            result = showInput("Zadajte id knihy");
            if (result != null) {
                if (!result.isEmpty()) {

                    int cis = Integer.parseInt(result);
                    list = core.findKnihuOfPobocka(getPobocku(), cis);
                }
            }
        }
        refreshTabKniha(list);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void nastBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastBtnResetActionPerformed
        core = new Core();
        ArrayList list = new ArrayList();
        refreshTabPoboc(list);
        refreshTabKniha(list);
        refreshTabPobPoz(list);
        refreshTabAllKnih(list);
        refreshTabCit(list);
        refreshTabCitPoz(list);
    }//GEN-LAST:event_nastBtnResetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        refreshTabPobPoz();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Nastavenie kolko nasledovnikov sa ma vypisat
     *
     * @param evt
     */
    private void nasTxtPocNasledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nasTxtPocNasledFocusLost
        String str = nasTxtPocNasled.getText();
        core.setPocNasledovnikov(Integer.parseInt(str));
    }//GEN-LAST:event_nasTxtPocNasledFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        refreshTabCit();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String str = citTxtId.getText();

        if (str.isEmpty()) {
            showErr("Nezadali ste Id čitatela!");
            return;
        }

        int cis = Integer.parseInt(str);
        refreshTabCit(core.findCitatelArray(cis));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        refreshTabPobPoz(core.getDelayPozKnih(getPobocku(), dateChooser.getCurrent()));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        String txt = knTxtHladaj.getText();
        if (txt.isEmpty()) {

            showErr("Nevyplnili ste id knihy!");
            return;
        }
        int id = Integer.parseInt(txt);
        refreshTabAllKnih(core.findKnihuAllArray(id));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nazov = showInput("Zadajte nazov pobocky");
        if (nazov != null) {
            core.vratKnihu(getIdKnihyAll(), nazov, dateChooser.getCurrent());
            //refreshTabCitPoz();
            refreshTabKniha();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        core.removeKniha(getIdKnihyAll());
        refreshTabAllKnih();
        refreshTabKniha();

    }//GEN-LAST:event_jButton9ActionPerformed

    private void citBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citBtnDelActionPerformed

        core.removeCitatel(getIdCitatela());

        refreshTabCit();


    }//GEN-LAST:event_citBtnDelActionPerformed

    /**
     * Vrati nazov aktulane oznacenej pobocky
     *
     * @return
     */
    public String getPobocku() {

        int row = tabPobocky.getSelectedRow();

        if (row > -1) {

            String name = (String) modelPob.getValueAt(row, PobockaTableModel.name);
            return name;

        } else {

            showErr("Nie je vybratá žiadna pobočka");
            return "";

        }

    }

    /**
     * Vrati nazov aktulane oznacenej knihy
     *
     * @return
     */
    public String getNazKnihy() {

        int row = pobTabKnihy.getSelectedRow();

        if (row > -1) {

            String name = (String) modelKnihy.getValueAt(row, KnihaTableModel.name);
            return name;

        } else {

            showErr("Nie je vybratá žiadna kniha");
            return "";

        }

    }
    
    /**
     * Vrati nazov aktulane oznacenej knihy
     *
     * @return
     */
    public int getIdKnihy() {

        int row = pobTabKnihy.getSelectedRow();

        if (row > -1) {

            int name = (int) modelKnihy.getValueAt(row, KnihaTableModel.id);
            return name;

        } else {

            showErr("Nie je vybratá žiadna kniha");
            return -1;

        }

    }

    /**
     * Vrati nazov aktulane oznacenej knihy
     *
     * @return
     */
    public int getIdKnihyAll() {

        int row = knihTbAll.getSelectedRow();

        if (row > -1) {

            int name = (int) modelAllKnihy.getValueAt(row, KnihaTableModel.id);
            return name;

        } else {

            showErr("Nie je vybratá žiadna kniha");
            return -1;

        }

    }

    /**
     * Vrati id aktulane oznaceneho citatela
     *
     * @return
     */
    public int getIdCitatela() {

        int row = tableCita.getSelectedRow();

        if (row > -1) {

            int cis = (int) modelCitatel.getValueAt(row, CitatelTableModel.id);
            return cis;

        } else {

            showErr("Nie je vybratý žiadny čitateľ");
            return -1;

        }

    }

    /**
     * Obnovenie tabulky pobociek
     */
    private void refreshTabPoboc() {
        refreshTabPoboc(core.getPobocky().getTableRows());

    }

    /**
     * Obnovenie tabulky
     *
     * @param list
     */
    private void refreshTabPoboc(ArrayList list) {
        tabPobocky.removeAll();
        if (list != null) {
            modelPob.setRows(list);
            tabPobocky.setModel(modelPob);
        }
        tabPobocky.repaint();
        tabPobocky.updateUI();

    }

    private void refreshTabKniha() {
        if (checkNazov.isSelected()) {
            refreshTabKniha(core.getKnihOfPobocka(getPobocku()));
        } else {

            refreshTabKniha(core.getKnihOfPobockaInt(getPobocku()));
        }
    }

    private void refreshTabKniha(ArrayList list) {
        pobTabKnihy.removeAll();
        if (list != null) {
            modelKnihy.setRows(list);
            pobTabKnihy.setModel(modelKnihy);
        }
        pobTabKnihy.repaint();
        pobTabKnihy.updateUI();

    }

    private void refreshTabAllKnih() {
        knihTbAll.removeAll();
        modelAllKnihy.setRows(core.getKnihy().getTableRows());
        knihTbAll.setModel(modelAllKnihy);
        knihTbAll.repaint();
        knihTbAll.updateUI();

    }

    private void refreshTabAllKnih(ArrayList list) {
        knihTbAll.removeAll();
        if (list != null) {
            modelAllKnihy.setRows(list);
            knihTbAll.setModel(modelAllKnihy);
        }
        knihTbAll.repaint();
        knihTbAll.updateUI();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkNazov;
    private javax.swing.JButton citBtnDel;
    private javax.swing.JButton citBtnPridaj;
    private javax.swing.JButton citBtnRefreshDown;
    private javax.swing.JTabbedPane citTabPanel;
    private javax.swing.JTextField citTxtId;
    private javax.swing.JTextField citTxtMeno;
    private javax.swing.JTextField citTxtPriez;
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JMenuItem fileBtnGener;
    private javax.swing.JMenuItem fileBtnLoad;
    private javax.swing.JMenuItem fileBtnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField knTxtHladaj;
    private javax.swing.JButton knihBtnRefres;
    private javax.swing.JTable knihTbAll;
    private javax.swing.JTextField nasTxtPocCit;
    private javax.swing.JTextField nasTxtPocKnih;
    private javax.swing.JTextField nasTxtPocNasled;
    private javax.swing.JTextField nasTxtPocPob;
    private javax.swing.JButton nastBtnReset;
    private javax.swing.JButton pobBtnAdd;
    private javax.swing.JButton pobBtnCount;
    private javax.swing.JButton pobBtnDel;
    private javax.swing.JButton pobBtnDelKnih;
    private javax.swing.JButton pobBtnHladajPob;
    private javax.swing.JButton pobBtnPozic;
    private javax.swing.JButton pobBtnRefreshKnih;
    private javax.swing.JButton pobPridKnih;
    private javax.swing.JTable pobTabKnihy;
    private javax.swing.JTable pobTablPozKnihy;
    private javax.swing.JTextField pobTxtNazov;
    private javax.swing.JTable tabPobocky;
    private javax.swing.JTable tableAktPozic;
    private javax.swing.JTable tableCita;
    private javax.swing.JTable tableHistPozic;
    private javax.swing.JTable tableOmesPoz;
    private javax.swing.JTextArea testAreaVypis;
    private javax.swing.JButton testBtnDelete;
    private javax.swing.JButton testBtnStart;
    private javax.swing.JTextField testTxtPocOper;
    private javax.swing.JTextField testTxtPravVloz;
    // End of variables declaration//GEN-END:variables

    /**
     * Zobrazi error msg
     *
     * @param msg text spravy
     */
    public void showErr(String msg) {

        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);

    }

    public void showInf(String msg) {

        JOptionPane.showMessageDialog(this, msg, "Info", JOptionPane.INFORMATION_MESSAGE);

    }

    public String showInput(String msg) {
        return JOptionPane.showInputDialog(this, msg);
    }

    public static void scrollToVisible(JTable table, int rowIndex, int vColIndex) {
        if (!(table.getParent() instanceof JViewport)) {
            return;
        }
        JViewport viewport = (JViewport) table.getParent();

        // This rectangle is relative to the table where the
        // northwest corner of cell (0,0) is always (0,0).
        Rectangle rect = table.getCellRect(rowIndex, vColIndex, true);

        // The location of the viewport relative to the table
        Point pt = viewport.getViewPosition();

        // Translate the cell location so that it is relative
        // to the view, assuming the northwest corner of the
        // view is (0,0)
        rect.setLocation(rect.x - pt.x, rect.y - pt.y);

        table.scrollRectToVisible(rect);

        // Scroll the area into view
        //viewport.scrollRectToVisible(rect);
    }

    private void refreshTabCit() {
        refreshTabCit(core.getCitatelia().getTableRows());
    }

    /**
     * Obnovenie tabulky citatel
     *
     * @param list
     */
    private void refreshTabCit(ArrayList list) {
        tableCita.removeAll();
        if (list != null) {
            modelCitatel.setRows(list);
            knihTbAll.setModel(modelCitatel);
        }
        tableCita.repaint();
        tableCita.updateUI();

    }

    /**
     * Tabulka pozicanych knih na pobocke
     *
     * @param list
     */
    private void refreshTabPobPoz() {
        pobTablPozKnihy.removeAll();

        modelPozKnihy.setRows(core.getPobPozKnihy(getPobocku()));
        pobTablPozKnihy.setModel(modelPozKnihy);

        pobTablPozKnihy.repaint();
        pobTablPozKnihy.updateUI();

    }

    /**
     * Tabulka pozicanych knih na pobocke
     *
     * @param list
     */
    private void refreshTabPobPoz(ArrayList list) {
        pobTablPozKnihy.removeAll();
        if (list != null) {
            modelPozKnihy.setRows(list);
            pobTablPozKnihy.setModel(modelPozKnihy);
        }
        pobTablPozKnihy.repaint();
        pobTablPozKnihy.updateUI();

    }

    /**
     * Tabulka pozicanych knih u citatela
     *
     * @param list
     */
    private void refreshTabCitPoz() {

        refreshTabCitPoz(core.getAktPozOfCitatel(getIdCitatela()));

    }

    /**
     * Tabulka pozicanych knih u citatela
     *
     * @param list
     */
    private void refreshTabCitPoz(ArrayList list) {
        tableAktPozic.removeAll();
        if (list != null) {
            modelAktPoz.setRows(list);
            tableAktPozic.setModel(modelAktPoz);
        }
        tableAktPozic.repaint();
        tableAktPozic.updateUI();

    }

    /**
     * Tabulka pozicanych knih u citatela
     *
     * @param list
     */
    private void refreshTabCitHistory() {
        tableHistPozic.removeAll();

        modelHistPoz.setRows(core.getCitHistry(getIdCitatela()));
        tableAktPozic.setModel(modelHistPoz);

        tableHistPozic.repaint();
        tableHistPozic.updateUI();

    }

    /**
     * Tabulka pozicanych knih u citatela
     *
     * @param list
     */
    private void refreshTabCitOmeskan() {
        tableOmesPoz.removeAll();

        modelOmesPoz.setRows(core.getCitOmeskania(getIdCitatela()));
        tableOmesPoz.setModel(modelOmesPoz);

        tableOmesPoz.repaint();
        tableOmesPoz.updateUI();

    }

    @Override
    public void onMessage(Message msg) {
        String title = msg.getType() == Message.ERROR ? "Chyba" : "Info";
        JOptionPane.showMessageDialog(this, msg.getMsg(), title, msg.getType());
    }

    /* posunutie v tabulke
     tabPobocky.changeSelection(0, 0, false, false);
     scrollToVisible(tabPobocky, 50, 1);
     tabPobocky.setRowSelectionInterval(50, 50);
     */
}
